# Generated by Django 4.2.29 on 2026-04-08 04:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_citizen_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizen_id',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Citizen ID must be exactly 13 digits', regex='^\\d{13}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
