# Generated by Django 4.2.29 on 2026-04-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holds', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hold',
            name='status',
            field=models.CharField(choices=[('pending', 'รอการยืนยัน'), ('confirmed', 'ยืนยันแล้ว - รอรับหนังสือ'), ('completed', 'เสร็จสิ้น'), ('expired', 'หมดอายุ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='holditem',
            name='status',
            field=models.CharField(choices=[('pending', 'รอการยืนยัน'), ('confirmed', 'ยืนยันแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20),
        ),
    ]
