# Generated by Django 4.2.29 on 2026-04-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='updated_at',
        ),
    ]
