# Generated by Django 4.2.29 on 2026-04-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('late_return', 'Late Return'), ('lost', 'Lost'), ('damaged', 'Damaged')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(help_text='Timestamp when fine was paid (also serves as creation time)')),
            ],
            options={
                'verbose_name': 'Fine',
                'verbose_name_plural': 'Fines',
                'db_table': 'fines',
                'ordering': ['-paid_at'],
            },
        ),
    ]
