# Generated by Django 4.2.29 on 2026-04-09 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        ('fines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='loan_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='loans.loanitem'),
        ),
    ]
