# Generated by Django 4.2.29 on 2026-04-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fine',
            name='type',
            field=models.CharField(choices=[('late_return', 'คืนช้า'), ('lost', 'หาย'), ('damaged', 'เสียหาย')], max_length=20),
        ),
    ]
