# Generated by Django 4.2.29 on 2026-04-04 19:42

from django.db import migrations, models
from django.utils import timezone


def set_paid_at_from_created_at(apps, schema_editor):
    """Copy created_at to paid_at for existing records."""
    Fine = apps.get_model('fines', 'Fine')
    for fine in Fine.objects.all():
        if not fine.paid_at:
            fine.paid_at = fine.created_at
            fine.save(update_fields=['paid_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fine',
            options={'ordering': ['-paid_at'], 'verbose_name': 'Fine', 'verbose_name_plural': 'Fines'},
        ),
        # First, populate paid_at from created_at for existing records
        migrations.RunPython(set_paid_at_from_created_at, migrations.RunPython.noop),
        # Then make paid_at non-nullable
        migrations.AlterField(
            model_name='fine',
            name='paid_at',
            field=models.DateTimeField(help_text='Timestamp when fine was paid (also serves as creation time)'),
        ),
        # Finally, remove the old fields
        migrations.RemoveField(
            model_name='fine',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='status',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='updated_at',
        ),
    ]
