# Generated by Django 4.2.29 on 2026-03-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationbatch',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Will be set by admin when confirming reservation', null=True),
        ),
    ]
