# Generated by Django 4.2.29 on 2026-04-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservationbatch_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationbatch',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiry time for confirmed reservation - user must pick up books before this time', null=True),
        ),
        migrations.AlterField(
            model_name='reservationbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
