# Generated by Django 4.2.29 on 2026-04-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_reservationbatch_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reservationbatch',
            name='updated_at',
        ),
    ]
