# Generated by Django 4.2.29 on 2026-04-08 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_publisher'),
        ('loans', '0009_remove_loanitem_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0008_remove_reservation_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiry time for confirmed hold - user must pick up books before this time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hold',
                'verbose_name_plural': 'Holds',
                'db_table': 'holds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HoldItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_items', to='books.book')),
                ('hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_items', to='reservations.hold')),
            ],
            options={
                'verbose_name': 'Hold Item',
                'verbose_name_plural': 'Hold Items',
                'db_table': 'hold_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='reservationbatch',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='ReservationBatch',
        ),
    ]
