# Generated by Django 4.2.29 on 2026-03-25 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Batch',
                'verbose_name_plural': 'Loan Batches',
                'db_table': 'loan_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('lost', 'Lost')], default='borrowed', max_length=20)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_items', to='books.book')),
                ('loan_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_items', to='loans.loanbatch')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_items', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Loan Item',
                'verbose_name_plural': 'Loan Items',
                'db_table': 'loan_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
