# Generated by Django 4.2.29 on 2026-04-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('active', 'กำลังยืม'), ('completed', 'เสร็จสิ้น')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanitem',
            name='status',
            field=models.CharField(choices=[('borrowed', 'กำลังยืม'), ('returned', 'คืนแล้ว'), ('lost', 'หาย')], default='borrowed', max_length=20),
        ),
    ]
