# Generated by Django 4.2.29 on 2026-04-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservation_status'),
        ('loans', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanitem',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_item', to='reservations.reservation'),
        ),
    ]
