# Generated by Django 4.2.29 on 2026-04-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loanitem_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanbatch',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
