# Generated by Django 4.2.29 on 2026-04-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loanbatch_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanbatch',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='loanitem',
            name='updated_at',
        ),
    ]
