# Generated by Django 4.2.29 on 2026-04-08 12:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0006_remove_loanbatch_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanBatch',
            new_name='Loan',
        ),
    ]
