# Generated by Django 4.2.29 on 2026-04-08 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0007_rename_loanbatch_loan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Loan', 'verbose_name_plural': 'Loans'},
        ),
        migrations.RenameField(
            model_name='loanitem',
            old_name='loan_batch',
            new_name='loan',
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='loan',
            table='loans',
        ),
    ]
