# Generated by Django 4.2.29 on 2026-04-08 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_alter_loan_options_rename_loan_batch_loanitem_loan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanitem',
            name='reservation',
        ),
    ]
