# Generated by Django 4.2.29 on 2026-04-08 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_hold_holditem_remove_reservationbatch_user_and_more'),
        ('loans', '0009_remove_loanitem_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanitem',
            name='hold_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_item', to='reservations.holditem'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loanitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
